using System;

namespace Simit.Resources.AppFonts
{
	// Generated by IconFont2Code: https://andreinitescu.github.io/IconFont2Code
	public static class SimitIcons
	{
		public const string ChatEmpty = "\u0061";
		public const string Abstract = "\ue800";
		public const string Calendar = "\ue801";
		public const string Comunicazioni = "\ue802";
		public const string Media = "\ue803";
		public const string Poster = "\ue804";
		public const string Slidekit = "\ue805";
		public const string Menu = "\ue806";
		public const string Info = "\ue807";
		public const string FrecciaDx = "\ue808";
		public const string Mail = "\ue809";
		public const string Clock = "\ue80a";
		public const string Rss = "\ue80b";
		public const string Attention = "\ue80c";
		public const string Close = "\ue80d";
		public const string Globe = "\ue80e";
		public const string InfoCircled = "\ue80f";
		public const string FacebookSquared = "\uf30e";
		public const string Instagram = "\uf32d";
	}
}
